# Generated by Django 5.0.1 on 2024-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('falculty', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('mat_no', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('date_created', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
