# Generated by Django 5.0.1 on 2024-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_remove_info_falculty_info_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
