# Generated by Django 5.0.1 on 2024-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_info_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='session',
            field=models.CharField(default='2020/2023', max_length=200),
        ),
    ]
