# Generated by Django 5.0.1 on 2024-01-25 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='falculty',
        ),
        migrations.AddField(
            model_name='info',
            name='faculty',
            field=models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('SCIENCE', 'SCIENCE')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
